name: Build and Deploy Events

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build events JSON
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          BANDSINTOWN_APP_ID: ${{ secrets.BANDSINTOWN_APP_ID }}
          BANDSINTOWN_PARTNER_ID: ${{ secrets.BANDSINTOWN_PARTNER_ID }}
          BANDSINTOWN_PARTNER_SECRET: ${{ secrets.BANDSINTOWN_PARTNER_SECRET }}
          SKIDDLE_API_KEY: ${{ secrets.SKIDDLE_API_KEY }}
          TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
        run: node scripts/build-events.mjs

      - name: Show generated files
        run: |
          echo "Listing web/…"
          ls -la web
          echo "upcoming.json head:"
          head -n 5 web/upcoming.json || true
          echo "past.json head:"
          head -n 5 web/past.json || true

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy JSON to Firebase Hosting (osiahevents)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: osiahevents # change this
        run: |
          firebase deploy --project "$FIREBASE_PROJECT_ID" --only hosting:osiahevents --token "$FIREBASE_TOKEN"
