name: Build and Deploy Events

on:
  schedule:
    - cron: "0 6 * * *" # daily 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run event builder
        run: node scripts/build-events.mjs
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          BANDSINTOWN_APP_ID: ${{ secrets.BANDSINTOWN_APP_ID }}
          BANDSINTOWN_ARTIST_ID: ${{ secrets.BANDSINTOWN_ARTIST_ID }}
          SKIDDLE_API_KEY: ${{ secrets.SKIDDLE_API_KEY }}
          TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}

      - name: Commit updated JSON files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add upcoming.json past.json || true
          git commit -m "Update event listings [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
